# Generated by Django 2.2.5 on 2019-11-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0019_auto_20191104_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaletters',
            name='Visa_Letter_N',
            field=models.CharField(default='<function Visaletters.number at 0x0000022AC73B15E8>', editable=False, max_length=200),
        ),
    ]
