# Generated by Django 2.2.5 on 2019-11-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0021_auto_20191104_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaletters',
            name='Visa_Letter_N',
            field=models.CharField(default='<function Visaletters.number at 0x0000022B1CE228B8>', editable=False, max_length=200),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
